# Generated by Django 3.0.2 on 2020-03-09 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_serialization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 9, 16, 33, 10, 899990)),
        ),
    ]
