# Generated by Django 3.0.2 on 2020-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_serialization', '0003_auto_20200309_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleObj',
            fields=[
                ('my_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
