# Generated by Django 3.0.2 on 2020-03-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testowner',
            name='owner',
        ),
        migrations.DeleteModel(
            name='WellnessEntry',
        ),
        migrations.DeleteModel(
            name='TestOwner',
        ),
    ]
